language: android
android:
  components:
    - platform-tools
    - tools
    - tools #not a typo. Needed for SDK update
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28

before_install:
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"

script:
  - ./gradlew build
